site_name: Tom's Cyber Journal
site_url: https://tominthebytes.github.io/Cyber-Journal
repo_url: https://github.com/TomInTheBytes/Cyber-Journal
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: amber
    accent: amber
  icon:
    # logo: fontawesome/solid/terminal
    logo: material/rocket-launch
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.instant
    - navigation.path
    - navigation.indexes 
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - toc.follow
plugins:
  - search
  - git-revision-date-localized
  - glightbox
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - admonition
  - attr_list
  - footnotes
  - def_list
  - tables
nav:
  - Home: index.md
  - Cheatsheets: 
    # - cheatsheets/index.md
    - OSCP: cheatsheets/oscp.md
    - Splunk: cheatsheets/splunk.md
  - Write-ups: 
    - writeups/index.md
    - writeups/hhc.md
    - writeups/splunk_bots.md
    - OSCP:
      - Proving Grounds:
        - Access: writeups/offsec/proving_grounds/access.md
        - Algernon: writeups/offsec/proving_grounds/algernon.md
        - Astronaut: writeups/offsec/proving_grounds/astronaut.md
        - Authby: writeups/offsec/proving_grounds/authby.md
        - Blackgate: writeups/offsec/proving_grounds/blackgate.md
        - Boolean: writeups/offsec/proving_grounds/boolean.md
        - Clue: writeups/offsec/proving_grounds/clue.md
        - Cockpit: writeups/offsec/proving_grounds/cockpit.md
        - Codo: writeups/offsec/proving_grounds/codo.md
        - Craft: writeups/offsec/proving_grounds/craft.md
        - Crane: writeups/offsec/proving_grounds/crane.md
        - Dvr4: writeups/offsec/proving_grounds/dvr4.md
        - Exfiltrated: writeups/offsec/proving_grounds/exfiltrated.md
        - Extplorer: writeups/offsec/proving_grounds/extplorer.md
        - Fired: writeups/offsec/proving_grounds/fired.md
        - Heist: writeups/offsec/proving_grounds/heist.md
        - Hepet: writeups/offsec/proving_grounds/hepet.md
        - Hub: writeups/offsec/proving_grounds/hub.md
        - Hutch: writeups/offsec/proving_grounds/hutch.md
        - Image: writeups/offsec/proving_grounds/image.md
        - Internal: writeups/offsec/proving_grounds/internal.md
        - Jacko: writeups/offsec/proving_grounds/jacko.md
        - Kevin: writeups/offsec/proving_grounds/kevin.md
        - Lavita: writeups/offsec/proving_grounds/lavita.md
        - Law: writeups/offsec/proving_grounds/law.md
        - Levram: writeups/offsec/proving_grounds/levram.md
        - Muddy: writeups/offsec/proving_grounds/muddy.md
        - Nickel: writeups/offsec/proving_grounds/nickel.md
        - Pc: writeups/offsec/proving_grounds/pc.md
        - Pelican: writeups/offsec/proving_grounds/pelican.md
        - Press: writeups/offsec/proving_grounds/press.md
        - Resourced: writeups/offsec/proving_grounds/resourced.md
        - Scrutiny: writeups/offsec/proving_grounds/scrutiny.md
        - Shenzi: writeups/offsec/proving_grounds/shenzi.md
        - Squid: writeups/offsec/proving_grounds/squid.md
        - Twiggy: writeups/offsec/proving_grounds/twiggy.md
  - Projects:
    - projects/index.md
    - Security Lab:
      # - projects/security_lab/index.md
      - Lab Architecture: projects/security_lab/architecture.md
      - Security Onion Overview: projects/security_lab/sec_onion.md
      - Research:
        - AnyFix Technique: projects/security_lab/research/anyfix.md
    - Generative AI:
      - Daily Intelligence Digest Automation (n8n): projects/genai/intel_digest_workflow.md
      - Threat Actor RAG and Assessment: projects/genai/intel_rag.md